# Generated by Django 2.2.2 on 2019-07-05 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Consulta')),
                ('horaInicio', models.TimeField(auto_now_add=True, verbose_name='Hora de inicio')),
                ('horaFinal', models.TimeField(null=True, verbose_name='Hora de Final')),
                ('observacionCons', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('precio', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Precio Base')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['fechaConsulta', 'horaInicio'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre del doctor')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=45, verbose_name='Dosis')),
                ('duracion', models.CharField(max_length=45, verbose_name='Duracion')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('observacionExp', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['paciente'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('marca_producto', models.CharField(max_length=30, verbose_name='Marca del producto')),
                ('existencia_producto', models.IntegerField(verbose_name='Exitencias')),
                ('precio_producto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precio unitario')),
                ('formafarmaceutica', models.CharField(max_length=30, verbose_name='Forma Farmaceutica')),
            ],
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('fechaUltimaModificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('notas', models.TextField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaccional.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTratamiento', models.CharField(max_length=100, verbose_name='Nombre del tratamiento')),
                ('descripcionTratamiento', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion del tratamiento')),
                ('precioBase', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Base')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['nombreTratamiento'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreReceta', models.CharField(default='Receta', max_length=100, verbose_name='Nombre de la receta')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccional.Consulta')),
                ('medicamento', models.ManyToManyField(through='transaccional.Especificacion', to='transaccional.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.IntegerField()),
                ('cara', models.CharField(choices=[('S', 'Vestibular'), ('C', 'Oclusal'), ('X', 'Pieza Completa'), ('Z', 'Distal'), ('D', 'Mesial'), ('I', 'Palatino')], max_length=4)),
                ('diagnostico', models.TextField()),
                ('notas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recomendado', 'Recomendado'), ('autorizado', 'Autorizado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='recomendado', max_length=12)),
                ('consulta_realizada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccional.Consulta')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccional.Odontograma')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccional.Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccional.Expediente')),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccional.Procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresPaciente', models.CharField(max_length=60, verbose_name='Nombres del paciente')),
                ('apellidosPaciente', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=None, max_length=2)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('referencia', models.CharField(blank=True, help_text='(En caso de ser niño)', max_length=60, null=True, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidosPaciente', 'nombresPaciente'],
                'unique_together': {('nombresPaciente', 'apellidosPaciente')},
            },
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de entrada')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de entrada')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccional.Medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='odontograma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccional.Odontograma'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaccional.Paciente'),
        ),
        migrations.AddField(
            model_name='especificacion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccional.Medicamento'),
        ),
        migrations.AddField(
            model_name='especificacion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccional.Receta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccional.Doctor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccional.Expediente'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuntoCita', models.CharField(max_length=50, verbose_name='Asunto de la cita')),
                ('fechaCita', models.DateField(verbose_name='Fecha de Cita')),
                ('horaCita', models.TimeField(verbose_name='Hora de Cita')),
                ('observacionCita', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccional.Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccional.Expediente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fechaCita', 'horaCita'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='Accion realizada')),
                ('fecha', models.DateTimeField(verbose_name='Fecha accion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
